print("Getting to know you!")
yourName = input("What's your name?")
favFood = input("What's your favorite food?")
favMusic = input("What's your favorite music?")
live = input("Where do you live?")

print("You are")
print(yourName)
print("You are probably hungry for")
print(favFood)
print("and you're definitely getting your groove on to")
print(favMusic)
print("living in the amazing")
print(live)